// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR4Y35EIAga3tQmg5uCDgzDIkU7iYJ1oo',
    appId: '1:149363528286:web:fb5c0747f0b815d1ec1acf',
    messagingSenderId: '149363528286',
    projectId: 'meowworldapp',
    authDomain: 'meowworldapp.firebaseapp.com',
    storageBucket: 'meowworldapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzaGfws8w1-AY20r81aTfVBipWhN_qoTI',
    appId: '1:149363528286:android:88b12b3fcc1d3fe4ec1acf',
    messagingSenderId: '149363528286',
    projectId: 'meowworldapp',
    storageBucket: 'meowworldapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH8SnAUw9OO8XkMwfle_poxgeRDI4xQ_Y',
    appId: '1:149363528286:ios:004a3f266ea6b669ec1acf',
    messagingSenderId: '149363528286',
    projectId: 'meowworldapp',
    storageBucket: 'meowworldapp.appspot.com',
    iosBundleId: 'com.example.meowWorldApp',
  );
}
